name: Build and test python

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"

    pull_request:
      paths-ignore:
        - "docs/**"
        - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "poetry"
    - run: poetry install --no-interaction
    - run: poetry install pytest pytest-cov black flake8 --no-interaction

    - name: Test with pytest
      run: poetry run pytest --cov .

    - name: Run black linter
      run: poetry run black src

    - name: Run flake8 linter
      run:
        poetry run flake8 . --exclude '.github','.venv','.pytest_cache' --max-complexity=10
        --max-line-length=120 --statistics

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3